# Docker
docker-hub-email: <<DOCKERHUB EMAIL>>
docker-hub-username: <<DOCKERHUB USERNAME>>
docker-hub-password: <<DOCKERHUB PASSWORD>>
docker-hub-repo-name: <<DOCKERHUB REPO>>

# Kubernetes
server: <<API SERVER URI>>
namespace: <<NAMESPACE>>
cad: <<CERT AUTH DATA>>
token: <<K8 TOKEN>>